Repository Anishukla/Hacktoberfest-2021-Data-Structures-and-Algorithms, pull requests merged in 2021-10, with the labels that each got.

#234 Added split linked list in parts
  Data Structures/LinkedList/SplitLinkedList.cpp
Labels: hacktoberfest-2021

#259 Added leetcode median of sorted array problem
  Leetcode/CPP/4. Median of Two Sorted Arrays.cpp
Labels: hacktoberfest-accepted, hacktoberfest-2021

#258 Feat: Rotate Array Solution
  Leetcode/JavaScript/rotate-array/README.md
  Leetcode/JavaScript/rotate-array/index.js
  Leetcode/JavaScript/rotate-array/index.spec.js
Labels: hacktoberfest-2021

#273 Added sudoku solver problem
  Leetcode/CPP/37. Sudoku Solver.cpp
Labels: hacktoberfest-2021

#272 Added leetcode 4Sum
  Leetcode/CPP/18. 4Sum.cpp
  Leetcode/CPP/28. Implement strStr().cpp
Labels: hacktoberfest-2021

#206 Solving Leetcode Problem 410. Split Array Largest Sum
  Leetcode/Java/410. Split Array Largest Sum.java
Labels: hacktoberfest-2021

#284 Added leetcode Unique Binary Search Trees
  Leetcode/CPP/96. Unique Binary Search Trees.cpp
Labels: hacktoberfest-accepted, hacktoberfest-2021

#294 Added leetcode group-anagram
  Leetcode/CPP/49. Group Anagrams.cpp
Labels: hacktoberfest-2021

#292 Added copy list with random pointer
  Data Structures/Stack/infixToPostfix.cpp
  Leetcode/CPP/138. Copy List with Random Pointer.cpp
Labels: hacktoberfest-accepted, hacktoberfest-2021

#307 Added C++ solution to 146. LRU Cache
  Leetcode/CPP/146. LRU Cache.cpp
Labels: hacktoberfest-accepted
